[build]
  base = "book-frontend"
  command = "npm run build"
  publish = "build"

[build.environment]
  REACT_APP_API_URL = https://book-search-5x6s.onrender.com

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
